blogging/urls.py
from django.urls import path
from .views import PostList, PostDetail, add_post


urlpatterns = [
    path("", PostList.as_view(), name="blog_index"),
    path("posts/<int:pk>/", PostDetail.as_view(), name="blog_detail"),
    path("add/", add_post, name="add_post"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("polling/", include("polling.urls")),
    path("", include("blogging.urls")),
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
]

polling/urls.py
from django.urls import path
from polling.views import PollListView, PollDetailView

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
]

blogging/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(
        blank=True, null=True, help_text="published time set to midnight"
    )

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/forms.py
from .models import Post
from django.forms import ModelForm, widgets


class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = []
        widgets = {"published_date": widgets.DateTimeInput(attrs={"type": "date"})}


# todo: get datetime widget working
# todo: add categories inline to add page

blogging/views.py
from .models import Post
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .forms import PostForm
from django.shortcuts import render, redirect


class PostList(ListView):
    model = Post
    template_name = "blogging/list.html"


class PostDetail(DetailView):
    model = Post
    template_name = "blogging/detail.html"

    def get_queryset(self):
        return Post.objects.exclude(published_date__exact=None)


def add_post(request):
    context = {}
    form = PostForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("blog_index")
        else:
            print(form.errors)
    context["form"] = form
    return render(request, "blogging/add.html", context)

polling/views.py
from django.shortcuts import render
from polling.models import Poll
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class PollListView(ListView):
    model = Poll
    template_name = "polling/list.html"


class PollDetailView(DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()
        if request.method == "POST":
            if request.POST.get("vote") == "Yes":
                poll.score += 1
            else:
                poll.score -= 1
            poll.save()
            context = {"object": poll}
            return render(request, "polling/detail.html", context)

blogging/templates/blogging/add.html
{% extends "base.html" %}
{% block content %}
<h1>Add a Post</h1>
<a href="/">Home</a>
<form method="post" >
{% csrf_token %}
{{form.as_p}}
<button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}

blogging/templates/blogging/detail.html
{% extends "base.html" %}
{% block content %}
<a class="backlink" href="/">Home</a>
<h1>{{ object }}</h1>
<div class="post-body">
   {{ object.text }}
</div>
<h6>
   <u>Categories:</u>
   {% for category in object.categories.all %}
   {% if forloop.last %}
   {{ category }}
   {% else %}
   {{ category }},
   {% endif %}
   {% endfor %}
</h6>
<p class="byline">
<h6><u>Posted By:</u> {{ object.author.username }} &mdash; {{ object.published_date }}
</h6>
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}
{% block content %}
<h1>Zeb's Blog</h1>
<a href="/add">Add a Post</a>
<h2>Published Posts:</h2>
{% for post in post_list %}
{% if post.published_date is not None %}
<div class="post">
   <h2>
      <a href="{% url 'blog_detail' post.pk %}">{{ post }}</a>
   </h2>
   <p class="byline">
   <h6>
      <u>Posted by: </u> {{ post.author.username }} &mdash; {{post.published_date }}
   </h6>
</div>
{% endif %}
{% endfor %}
<h6>Total Posts: {{post_list|length}}</h6>
<a href="/add">Add a Post</a>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
   <head>
      <title>Zeb's App</title>
      <link type='text/css' rel='stylesheet' href="{% static 'django_blog.css' %}">
   </head>
   <body>
      <div id="header">
         <ul id="control-bar">
            {% if user.is_authenticated %}
            {% if user.is_staff %}
            <li><a href="{% url 'admin:index' %}">admin</a></li>
            {% endif %}
            <li><a href="{% url 'logout' %}">logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">login</a></li>
            {% endif %}
         </ul>
      </div>
      <div id="container">
         <div id="content">
            {% block content %}
            [content will go here]
            {% endblock %}
         </div>
      </div>
   </body>
</html>

mysite/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>My Blog Login</h1>
<form action="" method="POST">{% csrf_token %}
<!--  csrf is cross site request forgery-->
  {{ form.as_p }}
  <p><input type="submit" value="Log In"></p>
</form>
{% endblock %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<div class="poll-body">
    {{ object.text }}
</div>
<div class="poll-score">
    Current score: {{ object.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}